#define memcpy_s(dest, dmax, src, slen) _memcpy_s_chk(dest, dmax, src, slen, dest, src)
#define memmove_s(dest, dmax, src, slen) _memmove_s_chk(dest, dmax, src, slen, dest, src)
#define memset_s(dest, dmax, value, n) _memset_s_chk(dest, dmax, value, n, dest)
#define memset16_s(dest, dmax, value, n) _memset16_s_chk(dest, dmax, value, n, dest)
#define memset32_s(dest, dmax, value, n) _memset32_s_chk(dest, dmax, value, n, dest)
#define memcmp_s(dest, dmax, src, slen, diff) _memcmp_s_chk(dest, dmax, src, slen, diff, dest, src)
#define memcmp16_s(dest, dlen, src, slen, diff) _memcmp16_s_chk(dest, dlen, src, slen, diff, dest, src)
#define memcmp32_s(dest, dlen, src, slen, diff) _memcmp32_s_chk(dest, dlen, src, slen, diff, dest, src)
#define memcpy16_s(dest, dmax, src, slen) _memcpy16_s_chk(dest, dmax, src, slen, dest, src)
#define memcpy32_s(dest, dmax, src, slen) _memcpy32_s_chk(dest, dmax, src, slen, dest, src)
#define memmove16_s(dest, dmax, src, slen) _memmove16_s_chk(dest, dmax, src, slen, dest, src)
#define memmove32_s(dest, dmax, src, slen) _memmove32_s_chk(dest, dmax, src, slen, dest, src)
#define memzero_s(dest, len) _memzero_s_chk(dest, len, dest)
#define memzero16_s(dest, len) _memzero16_s_chk(dest, len, dest)
#define memzero32_s(dest, len) _memzero32_s_chk(dest, len, dest)
#define memchr_s(dest, dmax, ch, result) _memchr_s_chk(dest, dmax, ch, result, dest)
#define memrchr_s(dest, dmax, ch, result) _memrchr_s_chk(dest, dmax, ch, result, dest)
#define memccpy_s(dest, dmax, src, c, n) _memccpy_s_chk(dest, dmax, src, c, n, dest, src)
